# fly.toml app configuration file generated for ball-bounce-buddies on 2023-06-23T19:49:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ball-bounce-buddies"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
